def label1 = "pl_scripted_docker_dind-${UUID.randomUUID().toString()}"
pipeline {
  agent {
    kubernetes {
      //cloud 'kubernetes'
      label 'pl_scripted_docker_dind'
      containerTemplate {
        name 'docker'
        image 'docker'
        ttyEnabled true
        command 'cat'
      }
    }
  }
  stages {
    stage('Run docker') {
      steps {
        container('docker') {
         
          sh 'docker --version'
          sh 'ls -l'
          sh 'docker build -f 'docker_in_docker/Dockerfile' .'
        }
      }
    }
  }
}
